// You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

        // var findDifference = function(s,t)
        // {
        //     let uniqueS = new Set(s); 
        //     let uniqueT = new Set(t);
        //     let difference = uniqueT.difference(uniqueS);;
        //     return difference ;
        // }
        // console.log(findDifference("abcd", "abcde")); 
        // console.log(findDifference("", "y"));
        
        // var findDifference = function(s, t)
        // {
        //     let stringS = s.split("").sort();
        //     let stringT = t.split("").sort();
        //     for(let i=0; i<stringT.length; i++)
        //     {
        //         if(stringS[i]!== stringT[i])
        //         {
        //             return stringT[i];
        //         }
        //     }
        //     return stringT[stringT.length-1];
            
        // }
        // console.log(findDifference("abcd", "abcde"));

        var findDifference = function(s,t)
        {
            let uniqueS = new Set(s); 
            let uniqueT = new Set(t);
            let difference = [...uniqueT].filter(char => !uniqueS.has(char));
            let output = difference.join('');
            return output ;
        }
        console.log(findDifference("abcd", "abcde")); 
        console.log(findDifference("", "y"));